library(data.table)
dt<-fread("household_power_consumption.txt")
setkey(dt,Date)
twodays<-dt[J(c('1/2/2007','2/2/2007')),]
subm1<-as.numeric(twodays[,Sub_metering_1])
subm2<-as.numeric(twodays[,Sub_metering_2])
subm3<-as.numeric(twodays[,Sub_metering_3])
datev<-strptime(paste(twodays[,Date],twodays[,Time], sep=' '),'%d/%m/%Y %H:%M:%S')
png("plot3.png",width=480,height=480)
par(mar=c(3,6,2,2))
plot(datev,subm1,xlab="",ylab='Energy sub metering',type="o",cex=0)
lines(datev,subm2,type="o",cex=0,col="red")
lines(datev,subm3,type="o",cex=0,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","blue","red"))
dev.off()